language: node_js
node_js:
- 14.15.3
cache:
  directories:
  - node_modules
before_install:
   - apk add make nasm autoconf automake libtool dpkg pkgconfig libpng libpng-dev g++
install: yarn
script: gatsby build
deploy: 
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: 'nick-chinsen'
  skip_cleanup: true
  region: us-east-2
  acl: public_read
  local_dir: public
  keep-history: true
  on:
    all_branches: true
#test comment